# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 軍事重地
subtitle: 程式、設計、3D
name: 大軍軍
description: 分享程式設計、平面設計、3D設計
email: daginryanliou@gmail.com
baseurl: "/ryanliouWebsite" # the subpath of your site, e.g. /blog
url: "https://danny80916kimo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: dagingingin
github_username:  danny80916kimo
instagram_username: danny80916kimo
# masthead_title: "My Custom Title"
logo: assets/images/logo.jpg
# Build settings
# No theme - using custom design
theme: null
search: true
atom_feed:
  hide: true
plugins:
  - jekyll-feed
  - jekyll-include-cache
breadcrumbs: true
breadcrumb_home_label : "Home"
breadcrumb_separator  : "/"

social:
  type: Person
  name: 大軍軍
  links:
    - "https://twitter.com/DAGINGINGIN"
    - "https://www.instagram.com/danny80916kimo/"

author:
  name     : "大軍軍"
  avatar   : "assets/images/logo.jpg"
  bio      : "一位iOS工程師，平時興趣喜歡研究技術、設計、3D及Motion Graphic"
  location : "Taiwan"
  links:
    - label: "Twitter"
      icon: "fa-brands fa-square-x-twitter"
      url: "https://twitter.com/DAGINGINGIN"
    - label: "GitHub"
      icon: "fa-brands fa-square-github"
      url: "https://github.com/danny80916kimo"
    - label: "Instagram"
      icon: "fa-brands fa-square-instagram"
      url: "https://www.instagram.com/danny80916kimo/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page

collections:
   art_works:
    output: true


include: ["_pages","_artworks"]
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - plans/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
